:global:
  componentName: openshift4-monitoring
  testMatrix:
    key: instance
    entries:
      - release-4.7
      - release-4.8
      - release-4.9
      - release-4.10

docs/antora.yml:
  name: openshift4-monitoring
  title: OpenShift4 Monitoring

.gitignore:
  additionalEntries:
    - manifests_requiring_prerendering/
    - jsonnetfile.json

.github/workflows/test.yaml:
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  makeTarget: test -e instance=${{ matrix.instance }}
